// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCollectionGame = "collection_games"

// CollectionGame mapped from table <collection_games>
type CollectionGame struct {
	ID           string `gorm:"column:id;primaryKey" json:"id"`
	CollectionID string `gorm:"column:collection_id;not null" json:"collection_id"`
	GameID       string `gorm:"column:game_id;not null" json:"game_id"`
}

// TableName CollectionGame's table name
func (*CollectionGame) TableName() string {
	return TableNameCollectionGame
}
