// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGame = "games"

// Game mapped from table <games>
type Game struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Title       string    `gorm:"column:title;not null" json:"title"`
	Description string    `gorm:"column:description" json:"description"`
	ReleaseDate time.Time `gorm:"column:release_date" json:"release_date"`
	CoverURL    string    `gorm:"column:cover_url" json:"cover_url"`
	Developer   string    `gorm:"column:developer" json:"developer"`
	Publisher   string    `gorm:"column:publisher" json:"publisher"`
	IgdbID      int64     `gorm:"column:igdb_id;not null" json:"igdb_id"`
	CreatedAt   time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
	Slug        string    `gorm:"column:slug;not null" json:"slug"`
}

// TableName Game's table name
func (*Game) TableName() string {
	return TableNameGame
}
