// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGameStat = "game_stats"

// GameStat mapped from table <game_stats>
type GameStat struct {
	GameID       string  `gorm:"column:game_id;primaryKey" json:"game_id"`
	AvgRating    float64 `gorm:"column:avg_rating" json:"avg_rating"`
	ReviewsCount int32   `gorm:"column:reviews_count" json:"reviews_count"`
	BacklogCount int32   `gorm:"column:backlog_count" json:"backlog_count"`
	PlayingCount int32   `gorm:"column:playing_count" json:"playing_count"`
	PlayedCount  int32   `gorm:"column:played_count" json:"played_count"`
	DroppedCount int32   `gorm:"column:dropped_count" json:"dropped_count"`
}

// TableName GameStat's table name
func (*GameStat) TableName() string {
	return TableNameGameStat
}
