// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGameGenre = "game_genres"

// GameGenre mapped from table <game_genres>
type GameGenre struct {
	ID      string `gorm:"column:id;primaryKey" json:"id"`
	GameID  string `gorm:"column:game_id;not null" json:"game_id"`
	GenreID string `gorm:"column:genre_id;not null" json:"genre_id"`
}

// TableName GameGenre's table name
func (*GameGenre) TableName() string {
	return TableNameGameGenre
}
