// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGamePlatform = "game_platforms"

// GamePlatform mapped from table <game_platforms>
type GamePlatform struct {
	ID           string `gorm:"column:id;primaryKey" json:"id"`
	GameID       string `gorm:"column:game_id;not null" json:"game_id"`
	PlatformName string `gorm:"column:platform_name;not null" json:"platform_name"`
}

// TableName GamePlatform's table name
func (*GamePlatform) TableName() string {
	return TableNameGamePlatform
}
