// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHowlongtobeatDatum = "howlongtobeat_data"

// HowlongtobeatDatum mapped from table <howlongtobeat_data>
type HowlongtobeatDatum struct {
	ID                  string    `gorm:"column:id;primaryKey" json:"id"`
	GameID              string    `gorm:"column:game_id;not null" json:"game_id"`
	HltbID              int64     `gorm:"column:hltb_id;not null" json:"hltb_id"`
	MainStoryHours      float64   `gorm:"column:main_story_hours" json:"main_story_hours"`
	MainStorySidesHours float64   `gorm:"column:main_story_sides_hours" json:"main_story_sides_hours"`
	CompletionistHours  float64   `gorm:"column:completionist_hours" json:"completionist_hours"`
	CreatedAt           time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt           time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName HowlongtobeatDatum's table name
func (*HowlongtobeatDatum) TableName() string {
	return TableNameHowlongtobeatDatum
}
