// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReviewLike = "review_likes"

// ReviewLike mapped from table <review_likes>
type ReviewLike struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	ReviewID  string    `gorm:"column:review_id;not null" json:"review_id"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	CreatedAt time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName ReviewLike's table name
func (*ReviewLike) TableName() string {
	return TableNameReviewLike
}
