// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReview = "reviews"

// Review mapped from table <reviews>
type Review struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	GameID    string    `gorm:"column:game_id;not null" json:"game_id"`
	Body      string    `gorm:"column:body" json:"body"`
	Rating    float64   `gorm:"column:rating;not null" json:"rating"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Review's table name
func (*Review) TableName() string {
	return TableNameReview
}
