// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUsersSocialLink = "users_social_links"

// UsersSocialLink mapped from table <users_social_links>
type UsersSocialLink struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	Platform  string    `gorm:"column:platform;not null" json:"platform"`
	URL       string    `gorm:"column:url;not null" json:"url"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName UsersSocialLink's table name
func (*UsersSocialLink) TableName() string {
	return TableNameUsersSocialLink
}
