// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserGame = "user_games"

// UserGame mapped from table <user_games>
type UserGame struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	GameID    string    `gorm:"column:game_id;not null" json:"game_id"`
	Status    string    `gorm:"column:status;not null" json:"status"`
	Rating    float64   `gorm:"column:rating" json:"rating"`
	CreatedAt time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName UserGame's table name
func (*UserGame) TableName() string {
	return TableNameUserGame
}
