// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserActivity = "user_activity"

// UserActivity mapped from table <user_activity>
type UserActivity struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	GameID    string    `gorm:"column:game_id;not null" json:"game_id"`
	ReviewID  string    `gorm:"column:review_id" json:"review_id"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName UserActivity's table name
func (*UserActivity) TableName() string {
	return TableNameUserActivity
}
