// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID                string    `gorm:"column:id;primaryKey" json:"id"`
	Username          string    `gorm:"column:username;not null" json:"username"`
	Email             string    `gorm:"column:email;not null" json:"email"`
	PasswordHash      string    `gorm:"column:password_hash" json:"password_hash"`
	SteamID           string    `gorm:"column:steam_id" json:"steam_id"`
	ProfilePictureURL string    `gorm:"column:profile_picture_url" json:"profile_picture_url"`
	Bio               string    `gorm:"column:bio" json:"bio"`
	CreatedAt         time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at" json:"updated_at"`
	EmailVerified     bool      `gorm:"column:email_verified;not null" json:"email_verified"`
	Role              string    `gorm:"column:role;not null" json:"role"`
	DisplayUsername   string    `gorm:"column:display_username;not null" json:"display_username"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
